/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hemant.jlambda;

import com.hemant.jlambda.events.Event;
import com.hemant.jlambda.events.Generate;
import com.hemant.jlambda.model.LambdaConfig;
import com.hemant.jlambda.runner.EventsRunner;
import com.hemant.jlambda.runner.EventsRunner.ExecuteEvents;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

import static com.hemant.jlambda.runner.EventsRunner.ExecuteEvents.GENERATE;

@Command(name = "jlambda")
public class App implements Runnable {

    @Option(names = {"-h", "--help"}, usageHelp = true)
    private boolean help;

    @Option(names = {"-i", "--intent"}, paramLabel = "event")
    private ExecuteEvents intent;

    private Event generateEvent = new Generate();

    public static void main(String[] args) {
        new CommandLine(new App()).setCaseInsensitiveEnumValuesAllowed(true).execute(args);
    }

    @Override
    public void run() {
        switch (intent) {
            case GENERATE:
                EventsRunner.run(() -> generateEvent.execute(new LambdaConfig("test")));
        }
    }
}
