/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hemant.jlambda;

import com.hemant.jlambda.events.Event;
import com.hemant.jlambda.events.Generate;
import com.hemant.jlambda.model.LambdaConfig;
import com.hemant.jlambda.runner.EventsRunner;
import com.hemant.jlambda.runner.ParsedIntent;
import com.hemant.jlambda.runner.PropertyLoader;
import picocli.CommandLine;
import picocli.CommandLine.ArgGroup;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(name = "jlambda")
public class App implements Runnable {

    @Option(names = {"-h", "--help"}, usageHelp = true)
    private boolean help;

    @ArgGroup(exclusive = true, multiplicity = "1")
    private ParsedIntent intent;

    @Option(names = {"-e", "--env"}, description = "The name of the profile based on which properties are loaded\n" +
            "For e.g. 1) default.properties -->When profile not set\n" +
            "2) dev.properties", defaultValue = "default")
    private String profile;

    public static void main(String[] args) {
        new CommandLine(new App()).setCaseInsensitiveEnumValuesAllowed(true).execute(args);
    }

    @Override
    public void run() {

        EventsRunner.build()
                    .withIntent(intent)
                    .run();
    }
}
